spring:
  application:
    name: GestorRH-API
  profiles:
    active: dev

  # LOGS
  security:
    user:
      name: usuario_ignorado
      password: sin_uso
  jpa:
    open-in-view: false

  # CONFIGURACIÓN DE SUBIDA DE ARCHIVOS
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB

server:
  port: 8080

# RUTA RELATIVA PARA JUSTIFICANTES
file:
  upload-dir: uploads/ausencias

# CONFIGURACIÓN DE SEGURIDAD (JWT). Si se lleva a produccion hay que quitar esta clave de aqui
jwt:
  secret: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
  expiration: 86400000

# CONFIGURACIÓN DE SWAGGER / OPENAPI
springdoc:
  swagger-ui:
    tags-sorter: alpha
    operations-sorter: method