spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/gestion_plantillas
    username: admin_rh
    password: password_rh
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

logging:
  file:
    name: logs/gestorrh-dev.log
  logback:
    rollingpolicy:
      max-file-size: 10MB
      max-history: 30
  level:
    root: WARN
    com.gestorrh.api.controller: INFO
    com.gestorrh.api.service: INFO
    com.gestorrh.api.exception: INFO
    com.gestorrh.api.config: INFO